---
title: "An Introduction to R"
author: Jarren Santos
date: "last updated 05/23/2019"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

## 00: Outline

**01: R & RStudio**

* Accessing R & RStudio
  * RStudio UI

**02: Things you can do in R & RStudio**

* R file types
  * `.R` scripts vs. `.Rmd` files
  * Other file types
* RActivities
  * Expressions
    * Data types
  * Object assignment
  * Functions
  
**03: Data Structures & Attributes**

* Data structures
* Attributes
  * Basic attributes

**04: Data Manipulation**

* Importing/exporting data
* Modifying variables
  * Indexing
  * Subsetting data
    * Logical conditions
* Recycling Rule

**05: Programming Efficiency & Style**

* Formatting
* Naming
* [Google R Style Guide](https://google.github.io/styleguide/Rguide.xml)
* [Data Organization in Spreadsheets](https://www.biostat.wisc.edu/~kbroman/publications/dataorg.pdf)

**06: On Your Own**

* Assigned activities that you must complete

## 01: R & RStudio

* Accessing R & RStudio
  * RStudio UI
    * [RStudio Overview](https://www.rstudio.com/products/rstudio/)
      * [RStudio Additional Features](https://www.rstudio.com/products/rstudio/features/)
    * Read through [Chapter 3.4 of "Getting used to R, RStudio, and R Markdown"](https://ismayc.github.io/rbasics-book/3-rstudiobasics.html#rstudio-layout)

## 02: Things you can do in R & RStudio

* R file types
  * `.R` scripts vs. `.Rmd` files
  * Other file types
    * Shiny apps
    * Plain `.md` files
    * Misc.

* RActivities
  * Expressions
    * Data types
      * Numeric
      * Character
        * Factors
      * Logical
      * Date
      * Missing values
      * Type conversions
  * Object assignment
  * Functions
    * Understanding how a function works
      * Arguments (input)
      * Results (output)
    * Packages
      * [R Packages](https://rstudio-education.github.io/hopr/packages2.html)
      * [Updating R & Its Packages](https://rstudio-education.github.io/hopr/dataio.html)

## 03: Data Structures & Attributes

* Data structures
  * Vectors
  * Matrices
  * Lists
  * Data frames
* Attributes
  * Basic attributes
    * `dim()`
      * `nrow()`
      * `ncol()`
    * `colnames()`
    * `str()`
    * `summary()`

## 04: Data Manipulation

* Data Manipulation
  * Importing/exporting data
  * Modifying variables
    * Indexing
    * Subsetting data
      * Logical conditions
  * Recycling Rule

## 05: Programming Efficiency & Style

* Programming Efficiency & Style
  * Formatting
  * Naming
  * [Google R Style Guide](https://google.github.io/styleguide/Rguide.xml)
  * [Data Organization in Spreadsheets](https://www.biostat.wisc.edu/~kbroman/publications/dataorg.pdf)
  
## 06: On Your Own

**Read and go through the following materials:**

* [Set Up for R and RStudio](https://jjallaire.shinyapps.io/learnr-tutorial-00-setup/)
* Part 1 (Chapters 1-3) of Garrett Grolemund's ["Hands-On Programming with R"](https://rstudio-education.github.io/hopr/project-1-weighted-dice.html)
* Part 2 (Chapters 4-7) of Garrett Grolemund's ["Hands-On Programming with R"](https://rstudio-education.github.io/hopr/project-2-playing-cards.html)
* Chapter 5 of Chester Ismay's ["Getting used to R, RStudio, and R Markdown"](https://ismayc.github.io/rbasics-book/5-rmdanal.html)

**Answer the following questions that involve both R programming and reflection:**

1. Answer questions in either Option #1 or Option #2 of [Ryan Miller's On Your Own Questions in"A Crash Course in R"](https://remiller1450.github.io/s230s19/Intro_to_R.html)

2. Are there any items in this tutorial that you think need further clarification?

3. What are questions that you have related to R and RStudio that were not addressed in this tutorial?

## 07: Additional Resources & References

Additional Resources:

* [Deciphering Common R Errors](https://ismayc.github.io/rbasics-book/6-errors.html)

References:

* [Shonda's R Tutorials in Data Science](http://web.grinnell.edu/individuals/kuipers/stat2labs/RTutorials.html)
* [Ryan's Crash Course in R](https://remiller1450.github.io/s230s19/Intro_to_R.html)
* Brian Smith's Biostat Computing Materials
* [Hands-On Programming with R by Garrett Grolemund](https://rstudio-education.github.io/hopr/)
* [Getting used to R, RStudio, and R Markdown by Chester Ismay and Patrick C. Kennedy](https://ismayc.github.io/rbasics-book/index.html)
